baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Eric Winebrenner'
theme = 'ananke' 
 
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]

  [[menus.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menus.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menus.main]]
    name = "About"
    url = "/about/"
    weight = 3